PORT: 443
URL: wss://....
USERNAME: username
PASSWORD: pwd
ADDITIONAL_HEADERS:
  - data-partition-id: osdu
TOKEN: ACCESS_TOKEN
TOKEN_URL: https://.../token
TOKEN_GRANT_TYPE: ...
TOKEN_SCOPE: ...
TOKEN_REFRESH_TOKEN: ...
